### ISSUE TITLE
Convert Module Name to StorageDsc

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/StorageDsc#129]
As per recent DSC Resource Naming guidelines changes:
https://github.com/PowerShell/DscResources/blob/master/Naming.md

**Comment by timhaintz** [comment]
@PlagueHO I noticed the help wanted badge. Yell out if you want to send some things my way. Happy to help as long as you don't mind guiding the way again. :)

**Comment by johlju** [comment]
@timhaintz it would be awesome if you want to help out, we will guide you if you need help, just tag us and let us know what you need help with. Also, on any issue, just say that you want to work on it, or that you are working on it, and @PlagueHO will change the label from 'help wanted' to 'in progress' and we will await your PR. 😄

**Comment by PlagueHO** [comment]
Absolutely @timhaintz - the more the help the better and we're definitely keen to have more people like yourself contributing! So just pop a note in the issue if you want to work on it - all help is gratefully accepted! :grin: The more people contributing changes to these repos enables me to focus on the review (freeing up @johlju - who practically reviews every one of my changes on his own).

If you want more detail etc on a change feel free to pop a message in the issue and I'll provide some greater depth and context. In the case of this issue, we're starting to move all the DSC Resource Kit resources out of "x" (experimental) and using a new naming convention (see the link at the top).

The process for this is as per @johlju's message here (SqlServerDsc was the first repo to undergo this transformation): https://github.com/PowerShell/SqlServerDsc/pull/902#issuecomment-345773058

The good thing about this particular change is that it is mostly just renaming files and doing global search/replaces on the names of the resources/modules. But you will want to look at @johlju's instructions carefully as you need to rename your repo after making all the changes and making sure all tests continue to pass. Once complete I can then merge it and get @kwirkykat to rename this repo. We'd then need to update the Wiki as well.

I'm currently performing this process on another repo (https://github.com/PowerShell/xAdcsDeployment/pull/41) so you could look at the process there.

I hope that clarifies the process on this one!

**Comment by timhaintz** [comment]
Great, thanks @PlagueHO and @johlju will go through the links and try and get up to speed so I can help out a bit more.
Cheers. :D

**Comment by timhaintz** [comment]
@PlagueHO and @johlju I have forked the repo and made the changes. (https://github.com/timhaintz/xStorage) How do I get the tests to run from my repo? I don't want to make a pull request if my tests are failing. I can't run the test to check though.....
Thanks.

**Comment by johlju** [comment]
Create a account on AppVeyor, once logged in add a project and choose the fork on GitHub. When the fork is shown in AppVeyor project list then each time you push to your fork AppVeyor will see that and start running the tests. You can see the tests running in the AppVeyor console as well. 

For unit test you can run them locally on your dev machine if you like since they should be non-destructive (might be faster running them locally for testing purposes). 

If you are working on this issue renamin the repo, then you need to rename your fork, and after that connect then add that as a project in AppVeyor.

**Comment by timhaintz** [comment]
Thanks @johlju will work on it again tonight.

**Comment by timhaintz** [comment]
@PlagueHO @johlju https://github.com/PowerShell/xStorage/pull/142 created. Please let me know what I have missed or any updates that are required. Thanks, Tim.

**Comment by johlju** [comment]
Awesome work! I leave the review part to @PlagueHO. @PlagueHO let me know if you need any help reviewing.

**Comment by PlagueHO** [comment]
All done now! Thanks @johlju and @timhaintz ! Great stuff!

**Comment by timhaintz** [comment]
Thanks for all your help @PlagueHO and @johlju . Has been great.
