### ISSUE TITLE
xDiskAccessPath: Mounted disks get drive letter on reboot

### ISSUE THREAD

**Issue by IcedGoblin** [PowerShell/StorageDsc#145]
**Details of the scenario you tried and the problem that is occurring:**

We are currently using the xStorage 3.4.0.0 module with the xDiskAccessPath resource within Chef to mount disks to a folder path. This works fine however on reboot the mounted disks are also assigned drive letters. Looking at native PowerShell there is an option like `Set-Partition -NoDefaultDriveLetter $true` and I was wondering if there is an option to ensure no drive letters are assigned when using DSC.

**The DSC configuration that is using the resource (as detailed as possible):**
```
dsc_resource 'd_data' do
  resource :xDiskAccessPath
  module_name 'xStorage'
  module_version '3.4.0.0'
  property :diskid, '2'
  property :accesspath, 'D:\Data'
  property :FSFormat, 'NTFS'
  property :AllocationUnitSize, 65_536
  property :FSLabel, 'Data'
end

dsc_resource 'd_system' do
  resource :xDiskAccessPath
  module_name 'xStorage'
  module_version '3.4.0.0'
  property :diskid, '3'
  property :accesspath, 'D:\System'
  property :FSFormat, 'NTFS'
  property :AllocationUnitSize, 65_536
  property :FSLabel, 'System'
end

dsc_resource 'd_logs' do
  resource :xDiskAccessPath
  module_name 'xStorage'
  module_version '3.4.0.0'
  property :diskid, '4'
  property :accesspath, 'D:\Logs'
  property :FSFormat, 'NTFS'
  property :AllocationUnitSize, 65_536
end
```
**Version of the Operating System and PowerShell the DSC Target Node is running:**

Windows Server 2012 R2
PowerShell 5.1

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**

```
3.4.0.0
```

**Comment by PlagueHO** [comment]
Hi @IcedGoblin - thanks for raising this. This does sound like a switch we could add.

My question for the community: Should this switch default to "True"? E.g. should a drive letter be prevented from being assigned to the disk when using the DiskAccessPath (note: xDiskAccessPath has been renamed to DiskAccessPath in StorageDsc).

**Comment by johlju** [comment]
I vote for using the default `$true`, do not assign drive letters. I would think that if you want to use mount points, one reason is that there will potentially not be enough drive letters for the disks, meaning there will not be enough drive letters for all mount points.

**Comment by JoshuaJSwain** [comment]
Sorry I missed a proper handling of get-partition to get the state on first run. Small fix in https://github.com/PowerShell/StorageDsc/pull/198
