### ISSUE TITLE
Wiki hasn't updated to include OpticalDiskDriveLetter

### ISSUE THREAD

**Issue by timhaintz** [PowerShell/StorageDsc#147]
The Wiki page for StorageDsc doesn't have OpticalDiskDriveLetter available. The examples are available in: StorageDsc/Modules/StorageDsc/Examples/Resources/OpticalDiskDriveLetter/
Should the Wiki auto update?

From the Wiki page:
**Included resources**
-Disk
-DiskAccessPath
-MountImage
-WaitForDisk
-WaitForVolume

Thanks, Tim.

**Comment by PlagueHO** [comment]
Hi @timhaintz - the Wiki doesn't yet autoupdate. I've got an issue open over on DSCResources.Tests (where the Wiki is generated) to add code to do this - but haven't got to it. So at the moment I've got to update the Wiki manually. I'll do it now - thanks for raising this!

**Comment by PlagueHO** [comment]
This has now been resolved. Thanks @timhaintz
