### ISSUE TITLE
xWaitforDisk, xDisk: Format disk popup prompts after successful deployment

### ISSUE THREAD

**Issue by jacerm** [PowerShell/StorageDsc#148]
**Details of the scenario you tried and the problem that is occurring:**

I am deploying an Azure VM with data disks. I am wanting to format a data drive using a combination of the following resources and parameters (see snippet). 

The Azure VM successfully deploys and the DSC applies successfully. But accessing the VM for the first time, I am immediately prompted by a popup telling me to format the disk before use. And again has me input values for Size, AllocationUnitSize etc.

**The DSC configuration that is using the resource (as detailed as possible):**

```
xWaitforDisk Disk2 {
             DiskId = 2
             RetryIntervalSec = 10
             RetryCount = 60
        }
xDisk GDataDrive 
        {
            DiskId = 2
            DriveLetter = 'G'
            FSFormat = 'NTFS'
            Size = 250GB
            AllocationUnitSize = 64KB
            DependsOn = '[xWaitForDisk]Disk2'
        }
xWaitforVolume waitForGDrive
        {
             DriveLetter = "G"
             RetryIntervalSec = 10
             RetryCount = 60
        }
```

**Version of the Operating System and PowerShell the DSC Target Node is running:**

Windows Server 2016-Datacenter
Powershell 5.1

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**

xStorage 2.9.0

**Comment by PlagueHO** [comment]
Hi @jacerm - thanks for logging this - that is really useful info. Are you able to post the DSC configuration output? Are you able to check in Disk Manager if the disk has been prepared with GPT and partitioned at all?
