### ISSUE TITLE
Disk: Moving from xDisk attempts to create new partition in error

### ISSUE THREAD

**Issue by adhodgson1** [PowerShell/StorageDsc#151]
**Details of the scenario you tried and the problem that is occurring:**

I have a VM that comes up with some formatted volumes and some new disks.  i used to use xDisk to format the new disks and assign the correct drive letter to the volumes, because the disks that were already provisioned were being assigned the wrong drive letters.  I moved to StorageDsc and found this failed.

What I expected to happen was that the backup drive (which was assigned disk 4), but currently on volume letter F was then assigned letter G.  The data drive on disk 3 but on volume letter E would then be assigned volume letter F.  The server disk which is on disk 2 but not initialised at all would then be initialised and assigned drive letter E.

For some reason the DSC resource attempted to create a partition on the backup drive where no space existed to create the partition:

TimeCreated  : 5/3/2018 9:35:07 AM
ProviderName : Microsoft-Windows-DSC
Id           : 4252
Message      : Job {3B508F10-4EB5-11E8-A949-000D3AB1504F} : 
               MIResult: 1
               Error Message: Not enough available capacity
               Activity ID: {d6b567b4-cea0-4805-8a54-c49f8452a2d2}
               Message ID: StorageWMI 40000,New-Partition
               Error Category: 0
               Error Code: 1
               Error Type: MI

**The DSC configuration that is using the resource (as detailed as possible):**

    Disk "Mount backup drive" {
      DiskId = 4
      DriveLetter = 'G'
      FSLabel = 'Backups'
      DependsOn = @("[OpticalDiskDriveLetter]RemoveDvdRom", "[WaitforDisk]Wait for backup disk to become available")
    }

    Disk "Mount data drive" {
      DiskId = 3
      DriveLetter = 'F'
      FSLabel = 'Data'
      DependsOn = @("[WaitforDisk]Wait for data disk to become available", "[Disk]Mount backup drive")
    }

    Disk "MountServerDrive" {
      DiskId = 2
      DriveLetter = 'E'
      FSLabel = 'Server'
      DependsOn = @("[WaitforDisk]Wait for server disk to become available", "[Disk]Mount data drive")
    }

**Version of the Operating System and PowerShell the DSC Target Node is running:**

Windows Server 2016, WMF 5.1.

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**

4.0.0.0

**Comment by adhodgson1** [comment]
Not sure if this helps but on the disks I am seeing this with I have a small reserved partition at the beginning of the disk which is showing up as the first partition.  I am not sure if the resource is seeing this as not matching so it goes onto create the partition then fail instead of moving to the next partition?

**Comment by PlagueHO** [comment]
Hi @adhodgson1 - there were some breaking changes between 2.8.0.0 and 4.0.0.0 that changed the behavior of the Disk resource to handle more scenarios. Are you able to output the verbose logs of applying the resource so I can trace the path through the resource?

Based on the description of the state your disk, I would expect a second partition to be created using the rest of the free space on the disk and the new volume created in there.

Are you able to give me a bit more detail on the state of the disk by running:
```Powershell
Get-Disk -Number 4
Get-Partition -DiskNumber 4
Get-Partition -DiskNumber 4 | Get-Volume
```

And dumping the output here?

Thank you.

**Comment by adhodgson1** [comment]
Hi,

There is already a volume on the disk.  I am using the Disk resource to ensure the volume is assigned the correct drive letter, and format the drive if required.  I think at the moment it is trying to create a new partition on the drive.  Here is the output:

Get-Disk -Number 4

Number Friendly Name Serial Number                    HealthStatus         OperationalStatus      Total Size Partition
                                                                                                             Style
------ ------------- -------------                    ------------         -----------------      ---------- ----------
4      Msft Virtu...                                  Healthy              Online                      32 GB GPT


Get-Partition -DiskNumber 4


   DiskPath: \\?\scsi#disk&ven_msft&prod_virtual_disk#000002#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}

PartitionNumber  DriveLetter Offset                                        Size Type
---------------  ----------- ------                                        ---- ----
1                            17408                                       128 MB Reserved
2                G           135266304                                 31.87 GB Basic


Get-Partition -DiskNumber 4 | Get-Volume

DriveLetter FileSystemLabel FileSystem DriveType HealthStatus OperationalStatus SizeRemaining     Size
----------- --------------- ---------- --------- ------------ ----------------- -------------     ----
G           Backups         NTFS       Fixed     Healthy      OK                     31.47 GB 31.87 GB

**Comment by PlagueHO** [comment]
I realized I haven't followed up on this one!

Is it possible to output the verbose logs of the DSC run? It should show us the exact path through the resource that the code is taking.

**Comment by adhodgson1** [comment]
Sorry about this, I feel it should be easy to get the verbose info but can't seem to do this easily at present.  I have re-created the problem configuration so can do this if I get more info.

**Comment by PlagueHO** [comment]
You should be able to just apply the config using:
```powershell
Start-DscConfiguration -Path . -ComputerName Localhost -Wait -Force -Verbose
```

It should then just dump all the verbose logs to the console for you (you'd run this on the node you're applying the config to).

**Comment by adhodgson1** [comment]
Sorry about that, I am running using AutomationDSC so had to find the right command to run and went down a bit of a rabbit hole which got me confused. :(

So to recap:
New VM being spun up with 4 disks:
  - Disk 0 = OS;
  - Disk 1 = Azure Temp drive (automatically formatted);
  - Disk 2 = Server drive (new disk not formatted);
  - Disk 3 = data drive (attached disk, formatted);
  - Disk 4 = backup drive, attached disk, formatted.

When server initially comes up:
  - Volume on Disk 0 attached to C:;
  - Volume on Disk 1 attached as D:;
  - No volume on disk 2 so not assigned drive letter, I need volume assigning to E:;
  - Volume on Disk 3 assigned E: I need F:;
  - Volume on Disk 4 assigned F: I need G:;
  - DVD assigned G:.

My DSC configuration:
    WaitforDisk "Wait for azure temp disk to become available" {
      DiskId = 1
      RetryIntervalSec = 60
      RetryCount = 10
    }
    
    WaitforDisk "Wait for server disk to become available" {
      DiskId = 2
      RetryIntervalSec = 60
      RetryCount = 10
    }

    WaitforDisk "Wait for data disk to become available" {
      DiskId = 3
      RetryIntervalSec = 60
      RetryCount = 10
    }

    WaitforDisk "Wait for backup disk to become available" {
      DiskId = 4
      RetryIntervalSec = 60
      RetryCount = 10
    }

    OpticalDiskDriveLetter RemoveDvdRom{
      DiskId      = 1
      DriveLetter = 'X' # This value is ignored as we are removing the resource
      Ensure      = 'Absent'
    }

    # Windows will try and mount the existing attached disks with the wrong drive letter,
    # so we need to mount in reverse drive letter order to allow correct letter assignment in one DSC pass.

    Disk "Mount backup drive" {
      DiskId = 4
      DriveLetter = 'G'
      FSLabel = 'Backups'
      DependsOn = @("[OpticalDiskDriveLetter]RemoveDvdRom", "[WaitforDisk]Wait for backup disk to become available")
    }

    Disk "Mount data drive" {
      DiskId = 3
      DriveLetter = 'F'
      FSLabel = 'Data'
      DependsOn = @("[WaitforDisk]Wait for data disk to become available", "[Disk]Mount backup drive")
    }

    Disk "MountServerDrive" {
      DiskId = 2
      DriveLetter = 'E'
      FSLabel = 'Server'
      DependsOn = @("[WaitforDisk]Wait for server disk to become available", "[Disk]Mount data drive")
    }

Using version 2.8.0.0 of xStorage (and a custom script to remove DVD drive) this works fine, however with 5.0.0.0 of StorageDSC I get the following:

VERBOSE: [SERVERNAME]: LCM:  [ Start  Resource ]  [[WaitForDisk]Wait for azure temp disk to become available]
VERBOSE: [SERVERNAME]: LCM:  [ Start  Test     ]  [[WaitForDisk]Wait for azure temp disk to become available]
VERBOSE: [SERVERNAME]:                            [[WaitForDisk]Wait for azure temp disk to become available]
Test-TargetResource: Checking for disk with Number '1'.
VERBOSE: [SERVERNAME]:                            [[WaitForDisk]Wait for azure temp disk to become available]
Test-TargetResource: Found disk with Number '1' named 'Virtual HD'.
VERBOSE: [SERVERNAME]: LCM:  [ End    Test     ]  [[WaitForDisk]Wait for azure temp disk to become available]  in
4.8280 seconds.
VERBOSE: [SERVERNAME]: LCM:  [ Skip   Set      ]  [[WaitForDisk]Wait for azure temp disk to become available]
VERBOSE: [SERVERNAME]: LCM:  [ End    Resource ]  [[WaitForDisk]Wait for azure temp disk to become available]
VERBOSE: [SERVERNAME]: LCM:  [ Start  Resource ]  [[WaitForDisk]Wait for server disk to become available]
VERBOSE: [SERVERNAME]: LCM:  [ Start  Test     ]  [[WaitForDisk]Wait for server disk to become available]
VERBOSE: [SERVERNAME]:                            [[WaitForDisk]Wait for server disk to become available]
Test-TargetResource: Checking for disk with Number '2'.
VERBOSE: [SERVERNAME]:                            [[WaitForDisk]Wait for server disk to become available]
Test-TargetResource: Found disk with Number '2' named 'Msft Virtual Disk'.
VERBOSE: [SERVERNAME]: LCM:  [ End    Test     ]  [[WaitForDisk]Wait for server disk to become available]  in 0.5630
 seconds.
VERBOSE: [SERVERNAME]: LCM:  [ Skip   Set      ]  [[WaitForDisk]Wait for server disk to become available]
VERBOSE: [SERVERNAME]: LCM:  [ End    Resource ]  [[WaitForDisk]Wait for server disk to become available]
VERBOSE: [SERVERNAME]: LCM:  [ Start  Resource ]  [[WaitForDisk]Wait for data disk to become available]
VERBOSE: [SERVERNAME]: LCM:  [ Start  Test     ]  [[WaitForDisk]Wait for data disk to become available]
VERBOSE: [SERVERNAME]:                            [[WaitForDisk]Wait for data disk to become available]
Test-TargetResource: Checking for disk with Number '3'.
VERBOSE: [SERVERNAME]:                            [[WaitForDisk]Wait for data disk to become available]
Test-TargetResource: Found disk with Number '3' named 'Msft Virtual Disk'.
VERBOSE: [SERVERNAME]: LCM:  [ End    Test     ]  [[WaitForDisk]Wait for data disk to become available]  in 0.0310
seconds.
VERBOSE: [SERVERNAME]: LCM:  [ Skip   Set      ]  [[WaitForDisk]Wait for data disk to become available]
VERBOSE: [SERVERNAME]: LCM:  [ End    Resource ]  [[WaitForDisk]Wait for data disk to become available]
VERBOSE: [SERVERNAME]: LCM:  [ Start  Resource ]  [[WaitForDisk]Wait for backup disk to become available]
VERBOSE: [SERVERNAME]: LCM:  [ Start  Test     ]  [[WaitForDisk]Wait for backup disk to become available]
VERBOSE: [SERVERNAME]:                            [[WaitForDisk]Wait for backup disk to become available]
Test-TargetResource: Checking for disk with Number '4'.
VERBOSE: [SERVERNAME]:                            [[WaitForDisk]Wait for backup disk to become available]
Test-TargetResource: Found disk with Number '4' named 'Msft Virtual Disk'.
VERBOSE: [SERVERNAME]: LCM:  [ End    Test     ]  [[WaitForDisk]Wait for backup disk to become available]  in 0.0310
 seconds.
VERBOSE: [SERVERNAME]: LCM:  [ Skip   Set      ]  [[WaitForDisk]Wait for backup disk to become available]
VERBOSE: [SERVERNAME]: LCM:  [ End    Resource ]  [[WaitForDisk]Wait for backup disk to become available]
VERBOSE: [SERVERNAME]: LCM:  [ Start  Resource ]  [[OpticalDiskDriveLetter]RemoveDvdRom]
VERBOSE: [SERVERNAME]: LCM:  [ Start  Test     ]  [[OpticalDiskDriveLetter]RemoveDvdRom]
VERBOSE: [SERVERNAME]:                            [[OpticalDiskDriveLetter]RemoveDvdRom] Get-OpticalDiskDriveLetter:
 Using Get-CimInstance to get the drive letter of optical disk 1 in the system.
VERBOSE: [SERVERNAME]:                            [[OpticalDiskDriveLetter]RemoveDvdRom] Perform operation
'Enumerate CimInstances' with following parameters, ''namespaceName' = root\cimv2,'className' = Win32_CDROMDrive'.
VERBOSE: [SERVERNAME]:                            [[OpticalDiskDriveLetter]RemoveDvdRom] Operation 'Enumerate
CimInstances' complete.
VERBOSE: [SERVERNAME]:                            [[OpticalDiskDriveLetter]RemoveDvdRom] Test-TargetResource: The
optical disk 1 is assigned the drive letter 'G:' which should be removed. Change required.
VERBOSE: [SERVERNAME]: LCM:  [ End    Test     ]  [[OpticalDiskDriveLetter]RemoveDvdRom]  in 0.6410 seconds.
VERBOSE: [SERVERNAME]: LCM:  [ Start  Set      ]  [[OpticalDiskDriveLetter]RemoveDvdRom]
VERBOSE: [SERVERNAME]:                            [[OpticalDiskDriveLetter]RemoveDvdRom] Get-OpticalDiskDriveLetter:
 Using Get-CimInstance to get the drive letter of optical disk 1 in the system.
VERBOSE: [SERVERNAME]:                            [[OpticalDiskDriveLetter]RemoveDvdRom] Perform operation
'Enumerate CimInstances' with following parameters, ''namespaceName' = root\cimv2,'className' = Win32_CDROMDrive'.
VERBOSE: [SERVERNAME]:                            [[OpticalDiskDriveLetter]RemoveDvdRom] Operation 'Enumerate
CimInstances' complete.
VERBOSE: [SERVERNAME]:                            [[OpticalDiskDriveLetter]RemoveDvdRom] Perform operation 'Query
CimInstances' with following parameters, ''queryExpression' = SELECT * FROM Win32_Volume WHERE DriveLetter =
'G:','queryDialect' = WQL,'namespaceName' = root\cimv2'.
VERBOSE: [SERVERNAME]:                            [[OpticalDiskDriveLetter]RemoveDvdRom] Operation 'Query
CimInstances' complete.
VERBOSE: [SERVERNAME]:                            [[OpticalDiskDriveLetter]RemoveDvdRom] Set-TargetResource: The
optical disk 1 drive letter is 'G:', attempting to remove it.
VERBOSE: [SERVERNAME]:                            [[OpticalDiskDriveLetter]RemoveDvdRom] Perform operation 'Modify
CimInstance' with following parameters, ''namespaceName' = root/cimv2,'instance' = Win32_Volume: G:\ (DeviceID =
"\\?\Volume{2b24709a-7dda-11e8-a946-806e...)'.
VERBOSE: [SERVERNAME]:                            [[OpticalDiskDriveLetter]RemoveDvdRom] Operation 'Modify
CimInstance' complete.
VERBOSE: [SERVERNAME]: LCM:  [ End    Set      ]  [[OpticalDiskDriveLetter]RemoveDvdRom]  in 0.8280 seconds.
VERBOSE: [SERVERNAME]: LCM:  [ End    Resource ]  [[OpticalDiskDriveLetter]RemoveDvdRom]
VERBOSE: [SERVERNAME]: LCM:  [ Start  Resource ]  [[Disk]Mount backup drive]
VERBOSE: [SERVERNAME]: LCM:  [ Start  Test     ]  [[Disk]Mount backup drive]
VERBOSE: [SERVERNAME]:                            [[Disk]Mount backup drive] Test-TargetResource: Testing disk with
Number '4' status for drive letter 'G'.
VERBOSE: [SERVERNAME]:                            [[Disk]Mount backup drive] Test-TargetResource: Checking if disk
with Number '4' is initialized.
VERBOSE: [SERVERNAME]:                            [[Disk]Mount backup drive] Test-TargetResource: Drive G was not
found.
VERBOSE: [SERVERNAME]: LCM:  [ End    Test     ]  [[Disk]Mount backup drive]  in 0.9380 seconds.
VERBOSE: [SERVERNAME]: LCM:  [ Start  Set      ]  [[Disk]Mount backup drive]
VERBOSE: [SERVERNAME]:                            [[Disk]Mount backup drive] Set-TargetResource: Setting disk with
Number '4' status for drive letter 'G'.
VERBOSE: [SERVERNAME]:                            [[Disk]Mount backup drive] Set-TargetResource: Checking disk with
Number '4' partition style.
VERBOSE: [SERVERNAME]:                            [[Disk]Mount backup drive] Set-TargetResource: Disk with Number
'4' is already initialized with GPT.
VERBOSE: [SERVERNAME]:                            [[Disk]Mount backup drive] Set-TargetResource: Disk with Number
'4' does not contain a partition assigned to drive letter 'G'.
VERBOSE: [SERVERNAME]:                            [[Disk]Mount backup drive] Disk with Number '4' already contains
partitions, but size parameter is not specified.
VERBOSE: [SERVERNAME]:                            [[Disk]Mount backup drive] Set-TargetResource: Creating partition
on disk with Number '4' with drive letter 'G' using all free space.
Not enough available capacity
Activity ID: {eed4238b-ff27-44d7-8cae-8320de037478}
    + CategoryInfo          : NotSpecified: (StorageWMI:) [], CimException
    + FullyQualifiedErrorId : StorageWMI 40000,New-Partition
    + PSComputerName        : localhost

VERBOSE: [SERVERNAME]:                            [[Disk]Mount backup drive] Set-TargetResource: Changing volume 'G'
 label to 'Backups'.
VERBOSE: [SERVERNAME]:                            [[Disk]Mount backup drive] Set-TargetResource: Successfully
initialized 'G'.
VERBOSE: [SERVERNAME]: LCM:  [ End    Set      ]  [[Disk]Mount backup drive]  in 1.1200 seconds.
The PowerShell DSC resource '[Disk]Mount backup drive' with SourceInfo '::92::5::Disk' threw one or more
non-terminating errors while running the Set-TargetResource functionality. These errors are logged to the ETW channel
called Microsoft-Windows-DSC/Operational. Refer to this channel for more details.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : NonTerminatingErrorFromProvider
    + PSComputerName        : localhost

**Comment by adhodgson1** [comment]
Hi,

I have looked at this again and believe I can work around this issue by specifying the 'FSFormat' option which will stop the partition creation process on the existing drive.  I will try this next week.

**Comment by PlagueHO** [comment]
Awesome @adhodgson1 - I look forward to hearing about this to see if it can be resolved. Sorry for not looking back into this earlier!

**Comment by adhodgson1** [comment]
Hi,

I tried this unfortunately with the same results.  The resource is still trying to create a partition on the drive because Windows is allocating the existing volume on the disk a drive letter (incorrectly).  I need the following to happen which is working with the old resource version given the DSC block shown in the issue description:

- If the disk is blank create a new volume on the drive and assign it the drive letter (this works);
- If the disk is assigned the wrong drive letter (because we have attached the existing disk to a new VM), then don't touch the partition and assign the correct drive letter.

I am going to try this again with specifying the disk size but I didn't want to have to go down this road if I could avoid it.  i guess the old version of this resource is less rezillient to multiple volumes on the same disk.

**Comment by KCDeMag** [comment]
I found the "Not enough available capacity" DSC error in my instance was because the drive letters were not getting set properly when the drive was formatted. The Get-partition command didn't return any drive letters for the disk so I went back into Disk Management and right-clicked on the disk and selected "Change Drive Letter and Paths" which will let you specify the drive letter again. Once I set it again the machines passed the compliance.

**Comment by PlagueHO** [comment]
Thanks for the info @KCDeMag - the resource is supposed to assign the drive letters should be getting set when the volume is formatted. Any idea why this wasn't happening?

**Comment by olegd-superoffice** [comment]
I'm having exactly the same problem now and from reading this I still don't know if it is possible to solve with DSC without manually logging into VM and changing drive letters. The scenario is as described by @adhodgson1 here:

>     * If the disk is blank create a new volume on the drive and assign it the drive letter (this works);
>     * If the disk is assigned the wrong drive letter (because we have attached the existing disk to a new VM), then don't touch the partition and assign the correct drive letter.
