### ISSUE TITLE
Disk- Creating a new disk only respects drive letter param

### ISSUE THREAD

**Issue by eschrader** [PowerShell/StorageDsc#179]
>         WaitForDisk Disk2
>         {
>              DiskId = 2
>              RetryIntervalSec = 60
>              RetryCount = 60
>         }
>         Disk FVolume
>         {
>              DiskId = 2
>              DriveLetter = 'F'
>              FSLabel = 'DATA'
>              FSFormat = 'NTFS'
>              AllocationUnitSize = 64KB
>              DependsOn = '[WaitForDisk]Disk2'
>         }
> 

This code keeps creating a drive F (no label) in File System format RAW with full capacity. Why does it not apply the label?
![image](https://user-images.githubusercontent.com/18456293/48232266-e0f2a300-e365-11e8-9962-7e4b1ad1f7ba.png)

**Comment by eschrader** [comment]
Possibly related to #157

**Comment by eschrader** [comment]
Actually, I just waited about 27 minutes and its all fixed now it looks like. Maybe it just takes a long time?

> \\\"Message\\\":  \\\"The PowerShell DSC resource \\\\u0027[Disk]FVolume\\\\u0027 with SourceInfo \\\\u0027::15::9::Disk\\\\u0027 threw one or more non-terminating errors while running the Set-TargetResource functionality. These errors are logged to the ETW channel called Microsoft-Windows-DSC/Operational. Refer to this channel for more details.\\\",\\r\\n

**Comment by PlagueHO** [comment]
Hi @eschrader - it shouldn't usually take that long to partition and format a disk. It usually takes under 10 seconds. Was the disk a virtual disk? Could you ask DSC to output the verbose logs as that should tell us the particular disk task that is taking so long (e.g. the initialization, partitioning, volume creation).

**Comment by eschrader** [comment]
> Hi @eschrader - it shouldn't usually take that long to partition and format a disk. It usually takes under 10 seconds. Was the disk a virtual disk? Could you ask DSC to output the verbose logs as that should tell us the particular disk task that is taking so long (e.g. the initialization, partitioning, volume creation).

Yea I am using an Azure IaaS VM with a new data disk. I was using Azure Automation, so maybe that's why it took so long.
