### ISSUE TITLE
Temporarily mount ISOs to install software

### ISSUE THREAD

**Issue by Peter-B-Clark** [PowerShell/StorageDsc#73]
Hi,

We found installing software, certificates etc. from network shares was unreliable, but it worked every time if we mounted an ISO containing the necessary installers/files. We even created our own ISOs with certificates and modules we wanted to install. The snag is, DSC likes to implement things and keep them there, but we want to dismount the ISO when we're done with it. Otherwise, the ISO file is locked when we want to make a change to it, for example to change a certificate or a slipstreamed cumulative update.
The ideal scenario would be to mount the ISO as part of the Set-TargetResource element of the thing that needs the ISO and have DSC ensure that it is absent at the end of the installation. That way it wont get mounted every time, only when it finds that resource is not in the desired state.

So far, the best approach we've found is to use, for example,
`$result = Invoke-DscResource -Name xCertificateImport -Method Test `
and so on, and later have something like
`if(!($result.InDesiredState))
      { 
        xMountImage GlobalBinaryMount`
and so on to mount the ISO, with other installation stuff depending on the completion of that, and then a script resource dismounting it as we can't use DSC to both mount and unmount the same ISO.

So we do the test for the resource, and if it's not in the desired state we insert the step to mount the image and then invoke the resource, but we still can't unmount it at the end using xMountImage, we have to use a script.

Is there an elegant, DSC friendly way to temporarily mount an ISO (and this principle could be applied to anything else temporary that's only needed while something is being configured)? If not, should there be? we used to be able to get around it by using different names for the mount and unmount process, but that was breaking the DSC guidelines and since that loophole was closed, we're looking for the best way to accomplish this.

Thanks in advance for your help!

**Comment by Zuldan** [comment]
@Peter-B-Clark, here are some options...

1. Use xRemoteFile to download the install files / certificates to local location then use xPackage to install what you need locally. You could even package everything into a zip file then use xRemoteFile -> xArchive -> xPackage. We use this method as it's very stable. The zip file is only copied across the network if it's updated.

2. Create a custom DSC resource or script resource to handle your mounting.
